# Site
title: Docs docs

versions:
  - '1'

sidebar_categories:
  null:
    - index
    - formatting
  Technical:
    - setup
    - recipes
    - config
github_repo: apollographql/docs-docs
content_root: source

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.apollographql.com/docs/docs/
root: /docs/docs/

public_dir: public/docs/docs

